name = "Catppuccin Latte Light"
slug = "catppuccin-latte-light"
mode = "light"

[colors]
background = "#f8f9fc"
base = "#f8f9fc"
blue = "#005e90"
crust = "#e9ebef"
error = "#ba1a1a"
errorContainer = "#ffdad6"
flamingo = "#6470bd"
green = "#007991"
inverseOnSurface = "#eff1f4"
inversePrimary = "#93cdf6"
inverseSurface = "#2e3133"
klink = "#2e8fc3"
klinkSelection = "#308fc4"
knegative = "#607eff"
knegativeSelection = "#607eff"
kneutral = "#c794ff"
kneutralSelection = "#c794ff"
kpositive = "#00b8de"
kpositiveSelection = "#00b8df"
kvisited = "#2584d6"
kvisitedSelection = "#2984d7"
lavender = "#0077b7"
mantle = "#eff1f4"
maroon = "#2751f9"
mauve = "#005791"
neutral_paletteKeyColor = "#75777a"
neutral_variant_paletteKeyColor = "#71787f"
onBackground = "#191c1e"
onError = "#ffffff"
onErrorContainer = "#93000a"
onPrimary = "#ffffff"
onPrimaryContainer = "#00060c"
onPrimaryFixed = "#001e2e"
onPrimaryFixedVariant = "#004c6d"
onSecondary = "#ffffff"
onSecondaryContainer = "#526776"
onSecondaryFixed = "#071e2b"
onSecondaryFixedVariant = "#354958"
onSuccess = "#FFFFFF"
onSuccessContainer = "#0C1F13"
onSurface = "#191c1e"
onSurfaceVariant = "#41484e"
onTertiary = "#ffffff"
onTertiaryContainer = "#ffffff"
onTertiaryFixed = "#2e0a3b"
onTertiaryFixedVariant = "#5e3869"
outline = "#6e757c"
outlineVariant = "#c0c7ce"
overlay0 = "#a4a8ae"
overlay1 = "#91979d"
overlay2 = "#7f858b"
peach = "#8a4dff"
pink = "#057ee6"
primary = "#3e7b9f"
primaryContainer = "#417da2"
primaryFixed = "#c7e7ff"
primaryFixedDim = "#93cdf6"
primary_paletteKeyColor = "#417da2"
red = "#003ee0"
rosewater = "#7d76b1"
sapphire = "#037ba6"
scrim = "#000000"
secondary = "#4c6170"
secondaryContainer = "#cfe5f8"
secondaryFixed = "#cfe5f8"
secondaryFixedDim = "#b4c9db"
secondary_paletteKeyColor = "#657a8a"
shadow = "#000000"
sky = "#0082b6"
subtext0 = "#6e757c"
subtext1 = "#41484e"
success = "#4F6354"
successContainer = "#D1E8D5"
surface = "#f8f9fc"
surface0 = "#e1e3e7"
surface1 = "#cbced2"
surface2 = "#b7babf"
surfaceBright = "#f8f9fc"
surfaceContainer = "#edeef1"
surfaceContainerHigh = "#e7e8eb"
surfaceContainerHighest = "#e1e2e6"
surfaceContainerLow = "#f2f3f7"
surfaceContainerLowest = "#ffffff"
surfaceDim = "#d9dadd"
surfaceTint = "#236488"
surfaceVariant = "#dce3eb"
teal = "#007195"
term0 = "#9a9b9b"
term1 = "#005bcc"
term10 = "#00afce"
term11 = "#9a7cce"
term12 = "#3fbdb6"
term13 = "#1e85ec"
term14 = "#59a9d1"
term15 = "#27282b"
term2 = "#008ca5"
term3 = "#7e61b0"
term4 = "#009993"
term5 = "#006ac4"
term6 = "#3389ae"
term7 = "#202225"
term8 = "#0f0f0f"
term9 = "#0071fa"
tertiary = "#8f659a"
tertiaryContainer = "#8f659a"
tertiaryFixed = "#fad7ff"
tertiaryFixedDim = "#e6b6f1"
tertiary_paletteKeyColor = "#92689d"
text = "#191c1e"
yellow = "#008f68"

[roles]
background = "background"
background_alt = "surfaceDim"
surface = "surface"
surface_hover = "surfaceContainerHigh"
selection = "primaryContainer"
surface_variant = "surfaceVariant"
foreground = "text"
on_surface = "onSurface"
foreground_muted = "subtext1"
foreground_subtle = "subtext0"
primary = "primary"
primary_container = "primaryContainer"
on_primary = "onPrimary"
secondary = "secondary"
secondary_container = "secondaryContainer"
on_secondary = "onSecondary"
tertiary = "tertiary"
tertiary_container = "tertiaryContainer"
on_tertiary = "onTertiary"
outline = "outline"
accent = "primary"
error = "error"
warning = "yellow"
success = "success"
info = "blue"
