name = "Caelestia Default Dark"
slug = "caelestia-default-dark"
mode = "dark"

[colors]
background = "#0a0f0f"
base = "#0a0f0f"
blue = "#57cdda"
crust = "#090e0e"
error = "#fa746f"
errorContainer = "#871f21"
errorDim = "#c54d4a"
errorPaletteKeyColor = "#c84f4c"
flamingo = "#e3e4c5"
green = "#8df1df"
inverseOnSurface = "#515655"
inversePrimary = "#336764"
inverseSurface = "#f6faf9"
klink = "#00969e"
klinkSelection = "#00969e"
knegative = "#838f00"
knegativeSelection = "#838f00"
kneutral = "#34c359"
kneutralSelection = "#34c359"
kpositive = "#00beab"
kpositiveSelection = "#00beab"
kvisited = "#008ca9"
kvisitedSelection = "#008ca9"
lavender = "#86d9e7"
mantle = "#0a0f0f"
maroon = "#abbef0"
mauve = "#60cfe8"
neutralPaletteKeyColor = "#737877"
neutralVariantPaletteKeyColor = "#6e7978"
neutral_paletteKeyColor = "#737877"
neutral_variant_paletteKeyColor = "#6e7978"
onBackground = "#dce8e6"
onError = "#490006"
onErrorContainer = "#ff9993"
onPrimary = "#0d4845"
onPrimaryContainer = "#b8ede9"
onPrimaryFixed = "#0c4744"
onPrimaryFixedVariant = "#306461"
onSecondary = "#2c4543"
onSecondaryContainer = "#a9c5c2"
onSecondaryFixed = "#2b4442"
onSecondaryFixedVariant = "#47605e"
onSuccess = "#213528"
onSuccessContainer = "#D1E9D6"
onSurface = "#dce8e6"
onSurfaceVariant = "#a2adac"
onTertiary = "#2e5c72"
onTertiaryContainer = "#255369"
onTertiaryFixed = "#0b4156"
onTertiaryFixedVariant = "#2f5d73"
outline = "#6d7876"
outlineVariant = "#3f4a49"
overlay0 = "#434b4a"
overlay1 = "#505958"
overlay2 = "#5f6967"
peach = "#a9daac"
pink = "#bae2ff"
primary = "#9bd0cc"
primaryContainer = "#255b58"
primaryDim = "#8ec2bf"
primaryFixed = "#b7ede9"
primaryFixedDim = "#a9deda"
primaryPaletteKeyColor = "#4c807d"
primary_paletteKeyColor = "#4c807d"
red = "#8ab5ff"
rosewater = "#f1f3e5"
sapphire = "#70d7db"
scrim = "#000000"
secondary = "#b0ccc9"
secondaryContainer = "#27403e"
secondaryDim = "#a3bebc"
secondaryFixed = "#cce8e5"
secondaryFixedDim = "#bedad7"
secondaryPaletteKeyColor = "#627c7a"
secondary_paletteKeyColor = "#627c7a"
shadow = "#000000"
sky = "#93eae9"
subtext0 = "#6d7876"
subtext1 = "#a2adac"
success = "#B5CCBA"
successContainer = "#374B3E"
surface = "#0a0f0f"
surface0 = "#191f1e"
surface1 = "#282e2e"
surface2 = "#353d3c"
surfaceBright = "#242e2d"
surfaceContainer = "#131b1a"
surfaceContainerHigh = "#192120"
surfaceContainerHighest = "#1d2827"
surfaceContainerLow = "#0e1514"
surfaceContainerLowest = "#000000"
surfaceDim = "#0a0f0f"
surfaceTint = "#9bd0cc"
surfaceVariant = "#1d2827"
teal = "#9feee7"
term0 = "#343434"
term1 = "#769e00"
term10 = "#41f7d0"
term11 = "#cdffe9"
term12 = "#a3c8c3"
term13 = "#a2c0f7"
term14 = "#8bedd9"
term15 = "#ffffff"
term2 = "#56e2c0"
term3 = "#81fcce"
term4 = "#76b6b3"
term5 = "#7aaee9"
term6 = "#83d8c9"
term7 = "#cddcd3"
term8 = "#9aa59e"
term9 = "#85b900"
tertiary = "#d5efff"
tertiaryContainer = "#b6e3fe"
tertiaryDim = "#b6e3fe"
tertiaryFixed = "#b6e3fe"
tertiaryFixedDim = "#a8d5ef"
tertiaryPaletteKeyColor = "#517d94"
tertiary_paletteKeyColor = "#517d94"
text = "#dce8e6"
yellow = "#d3fae8"

[roles]
background = "background"
background_alt = "surfaceDim"
surface = "surface"
surface_hover = "surfaceContainerHigh"
selection = "primaryContainer"
surface_variant = "surfaceVariant"
foreground = "text"
on_surface = "onSurface"
foreground_muted = "subtext1"
foreground_subtle = "subtext0"
primary = "primary"
primary_container = "primaryContainer"
on_primary = "onPrimary"
secondary = "secondary"
secondary_container = "secondaryContainer"
on_secondary = "onSecondary"
tertiary = "tertiary"
tertiary_container = "tertiaryContainer"
on_tertiary = "onTertiary"
outline = "outline"
accent = "primary"
error = "error"
warning = "yellow"
success = "success"
info = "blue"
