hl.config({ animations = { enabled = true } })

hl.curve("tartarusStandard", { type = "bezier", points = { { 0.2, 0 }, { 0, 1 } } })
hl.curve("tartarusEmphasized", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("tartarusAccel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })

hl.animation({ leaf = "layersIn", enabled = true, speed = 5, bezier = "tartarusEmphasized", style = "slide" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 4, bezier = "tartarusAccel", style = "slide" })
hl.animation({ leaf = "fadeLayers", enabled = true, speed = 5, bezier = "tartarusStandard" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 5, bezier = "tartarusEmphasized" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "tartarusAccel" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 6, bezier = "tartarusStandard" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "tartarusStandard" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 4, bezier = "tartarusEmphasized", style = "slidefadevert 15%" })
hl.animation({ leaf = "fade", enabled = true, speed = 6, bezier = "tartarusStandard" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 6, bezier = "tartarusStandard" })
hl.animation({ leaf = "border", enabled = true, speed = 6, bezier = "tartarusStandard" })
