------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

------------------
---- MONITORS ----
------------------

-- Generated by Tartarus MonitorService after confirming a layout.
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

------------------
---- MONITORS ----
------------------

-- Generated by Tartarus MonitorService after confirming a layout.
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

------------------
---- MONITORS ----
------------------

-- Generated by Tartarus MonitorService after confirming a layout.
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

local MONITORS = {
    {
        output = "DP-2",
        mode = "1920x1080@164.96",
        position = "0x0",
        scale = 1,
        transform = 0,
    },

    {
        output = "HDMI-A-1",
        mode = "1920x1080@60.00",
        position = "1920x0",
        scale = 1,
        transform = 0,
    },

}

for _, monitor in ipairs(MONITORS) do
    hl.monitor(monitor)
end
