#!/usr/bin/env python3
"""Apply and persist validated Hyprland monitor layouts for Tartarus."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path


CONFIG_PATH = Path.home() / ".config/hypr/modules/monitors.lua"
STATE_DIR = Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local/state")) / "tartarus-shell/monitors"


def fail(message: str) -> int:
    print(message, file=sys.stderr)
    return 1


def load_layout(raw: str) -> list[dict]:
    value = json.loads(raw)
    if not isinstance(value, list) or not value:
        raise ValueError("El layout debe contener al menos un monitor")

    names: set[str] = set()
    active = 0
    for monitor in value:
        if not isinstance(monitor, dict):
            raise ValueError("Entrada de monitor inválida")
        name = str(monitor.get("name", "")).strip()
        if not name or name == "FALLBACK" or name in names:
            raise ValueError("Nombre de monitor inválido o duplicado")
        names.add(name)
        if not monitor.get("disabled", False):
            active += 1
        for key in ("x", "y", "transform"):
            if not isinstance(monitor.get(key), (int, float)):
                raise ValueError(f"{key} inválido para {name}")
        scale = float(monitor.get("scale", 1))
        if not 0.25 <= scale <= 5:
            raise ValueError(f"Escala fuera de rango para {name}")

    if active == 0:
        raise ValueError("No se puede desactivar todos los monitores")
    return value


def clean_mode(value: object) -> str:
    mode = str(value or "preferred").strip()
    return mode.removesuffix("Hz")


def monitor_spec(monitor: dict) -> str:
    name = monitor["name"]
    if monitor.get("disabled", False):
        return f"{name},disable"

    mode = clean_mode(monitor.get("mode"))
    position = f"{int(round(float(monitor['x'])))}x{int(round(float(monitor['y'])))}"
    scale = f"{float(monitor.get('scale', 1)):g}"
    transform = int(monitor.get("transform", 0)) % 8
    fields = [name, mode, position, scale, "transform", str(transform)]
    mirror = str(monitor.get("mirrorOf", "none") or "none")
    if mirror not in ("", "none"):
        fields.extend(["mirror", mirror])
    return ",".join(fields)


def apply_layout(layout: list[dict]) -> int:
    # Enable targets before disabling outputs. This keeps a valid output alive
    # while Hyprland remaps the virtual desktop.
    ordered = sorted(layout, key=lambda item: bool(item.get("disabled", False)))
    for monitor in ordered:
        result = subprocess.run(
            ["hyprctl", "keyword", "monitor", monitor_spec(monitor)],
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode != 0:
            message = result.stderr.strip() or result.stdout.strip() or "hyprctl rechazó el layout"
            return fail(f"{monitor['name']}: {message}")
    return 0


def lua_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def lua_layout(layout: list[dict]) -> str:
    lines = [
        "------------------",
        "---- MONITORS ----",
        "------------------",
        "",
        "-- Generated by Tartarus MonitorService after confirming a layout.",
        "-- See https://wiki.hypr.land/Configuring/Basics/Monitors/",
        "",
        "local MONITORS = {",
    ]
    for monitor in layout:
        position = f"{int(round(float(monitor['x'])))}x{int(round(float(monitor['y'])))}"
        lines.extend(
            [
                "    {",
                f"        output = {lua_string(monitor['name'])},",
                f"        mode = {lua_string(clean_mode(monitor.get('mode')))},",
                f"        position = {lua_string(position)},",
                f"        scale = {float(monitor.get('scale', 1)):g},",
                f"        transform = {int(monitor.get('transform', 0)) % 8},",
            ]
        )
        if monitor.get("disabled", False):
            lines.append("        disabled = true,")
        mirror = str(monitor.get("mirrorOf", "none") or "none")
        if mirror not in ("", "none"):
            lines.append(f"        mirror = {lua_string(mirror)},")
        lines.extend(["    },", ""])
    lines.extend(
        [
            "}",
            "",
            "for _, monitor in ipairs(MONITORS) do",
            "    hl.monitor(monitor)",
            "end",
            "",
        ]
    )
    return "\n".join(lines)


def persist_layout(layout: list[dict]) -> int:
    if not CONFIG_PATH.exists():
        return fail(f"No existe {CONFIG_PATH}")

    original = CONFIG_PATH.read_text(encoding="utf-8")
    replacement = lua_layout(layout)
    updated, count = re.subn(
        r"(?ms)^local MONITORS = \{.*?^\}\n\nfor _, monitor in ipairs\(MONITORS\) do\n    hl\.monitor\(monitor\)\nend\n?",
        replacement,
        original,
        count=1,
    )
    if count != 1:
        return fail("No se reconoció la estructura segura de monitors.lua; no se modificó")

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    shutil.copy2(CONFIG_PATH, STATE_DIR / f"monitors-{stamp}.lua")
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=CONFIG_PATH.parent, delete=False) as handle:
        handle.write(updated)
        temporary = Path(handle.name)
    os.replace(temporary, CONFIG_PATH)
    return 0


def main(argv: list[str]) -> int:
    if len(argv) != 3 or argv[1] not in {"apply", "persist"}:
        return fail("Uso: monitor-control.py apply|persist JSON_LAYOUT")
    try:
        layout = load_layout(argv[2])
        return apply_layout(layout) if argv[1] == "apply" else persist_layout(layout)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        return fail(str(error))


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
