name = "Caelestia Default Light"
slug = "caelestia-default-light"
mode = "light"

[colors]
background = "#f6faf9"
base = "#f6faf9"
blue = "#00636d"
crust = "#e9eceb"
error = "#a83836"
errorContainer = "#fa746f"
errorDim = "#67040d"
errorPaletteKeyColor = "#c84f4c"
flamingo = "#6f7c1e"
green = "#007d6d"
inverseOnSurface = "#999e9d"
inversePrimary = "#b0f8f3"
inverseSurface = "#0a0f0f"
klink = "#00969d"
klinkSelection = "#00969e"
knegative = "#838f00"
knegativeSelection = "#838f00"
kneutral = "#34c359"
kneutralSelection = "#34c359"
kpositive = "#00beab"
kpositiveSelection = "#00beac"
kvisited = "#008ca9"
kvisitedSelection = "#008ca9"
lavender = "#007e8b"
mantle = "#eef1f0"
maroon = "#606c00"
mauve = "#005d6c"
neutralPaletteKeyColor = "#737877"
neutralVariantPaletteKeyColor = "#6e7978"
neutral_paletteKeyColor = "#737877"
neutral_variant_paletteKeyColor = "#6e7978"
onBackground = "#2a3433"
onError = "#fff7f6"
onErrorContainer = "#6e0a12"
onPrimary = "#e1fffc"
onPrimaryContainer = "#015c59"
onPrimaryFixed = "#004845"
onPrimaryFixedVariant = "#166663"
onSecondary = "#e2fffc"
onSecondaryContainer = "#3d5654"
onSecondaryFixed = "#2b4442"
onSecondaryFixedVariant = "#47605e"
onSuccess = "#FFFFFF"
onSuccessContainer = "#0C1F13"
onSurface = "#2a3433"
onSurfaceVariant = "#566160"
onTertiary = "#f4faff"
onTertiaryContainer = "#255369"
onTertiaryFixed = "#0b4156"
onTertiaryFixedVariant = "#2f5d73"
outline = "#727d7c"
outlineVariant = "#a9b4b3"
overlay0 = "#a5aead"
overlay1 = "#949d9c"
overlay2 = "#828c8b"
peach = "#198900"
pink = "#0085c0"
primary = "#1c6a66"
primaryContainer = "#a8f0eb"
primaryDim = "#045d5a"
primaryFixed = "#a8f0eb"
primaryFixedDim = "#9ae1dc"
primaryPaletteKeyColor = "#3a827e"
primary_paletteKeyColor = "#3a827e"
red = "#515900"
rosewater = "#6b8647"
sapphire = "#008080"
scrim = "#000000"
secondary = "#4a6462"
secondaryContainer = "#cce8e5"
secondaryDim = "#3e5856"
secondaryFixed = "#cce8e5"
secondaryFixedDim = "#bedad7"
secondaryPaletteKeyColor = "#627c7a"
secondary_paletteKeyColor = "#627c7a"
shadow = "#000000"
sky = "#00878d"
subtext0 = "#727d7c"
subtext1 = "#566160"
success = "#4F6354"
successContainer = "#D1E8D5"
surface = "#f6faf9"
surface0 = "#e1e6e5"
surface1 = "#cbd1d0"
surface2 = "#b8bfbe"
surfaceBright = "#f6faf9"
surfaceContainer = "#e7f0ee"
surfaceContainerHigh = "#e1eae8"
surfaceContainerHighest = "#d9e5e3"
surfaceContainerLow = "#eef5f3"
surfaceContainerLowest = "#ffffff"
surfaceDim = "#d1dcdb"
surfaceTint = "#1c6a66"
surfaceVariant = "#d9e5e3"
teal = "#007573"
term0 = "#9a9b99"
term1 = "#005bcc"
term10 = "#00b49c"
term11 = "#5d9954"
term12 = "#52be9c"
term13 = "#008cca"
term14 = "#45b0ae"
term15 = "#25292a"
term2 = "#00907c"
term3 = "#427d3b"
term4 = "#269a7a"
term5 = "#0071a3"
term6 = "#128f8d"
term7 = "#1f2324"
term8 = "#0f0f0f"
term9 = "#0071fa"
tertiary = "#37647b"
tertiaryContainer = "#b6e3fe"
tertiaryDim = "#2a586e"
tertiaryFixed = "#b6e3fe"
tertiaryFixedDim = "#a8d5ef"
tertiaryPaletteKeyColor = "#517d94"
tertiary_paletteKeyColor = "#517d94"
text = "#2a3433"
yellow = "#008f67"

[roles]
background = "background"
background_alt = "surfaceDim"
surface = "surface"
surface_hover = "surfaceContainerHigh"
selection = "primaryContainer"
surface_variant = "surfaceVariant"
foreground = "text"
on_surface = "onSurface"
foreground_muted = "subtext1"
foreground_subtle = "subtext0"
primary = "primary"
primary_container = "primaryContainer"
on_primary = "onPrimary"
secondary = "secondary"
secondary_container = "secondaryContainer"
on_secondary = "onSecondary"
tertiary = "tertiary"
tertiary_container = "tertiaryContainer"
on_tertiary = "onTertiary"
outline = "outline"
accent = "primary"
error = "error"
warning = "yellow"
success = "success"
info = "blue"
